In [4]:

pkl_path = "/home/bobby/data/expert_demos/franka_env/put_bowl_into_basket_new_left_robot.pkl"
import pickle, pprint
import numpy as np
import cv2
with open(pkl_path, "rb") as f:
    data = pickle.load(f)
print(data.keys())
print(len(data['observations']))
# print(data['observations'][0].keys())
# print(data['observations'][0]['pixels4'][0])
# print(data['observations'][0]['cartesian_states'][1])

def to_uint8(img):
    img = np.asarray(img)
    if img.dtype != np.uint8:
        img = np.clip(img, 0, 255).astype(np.uint8)
    if img.ndim == 3 and img.shape[0] in (3,4) and img.shape[2] not in (3,4):
        # CHW -> HWC
        img = np.transpose(img, (1,2,0))
    if img.shape[0] != 256 or img.shape[1] != 256:
        img = cv2.resize(img, (256,256), interpolation=cv2.INTER_AREA)
    if img.shape[-1] == 4:  # RGBA -> RGB
        img = img[..., :3]
    return img
obs_list = data['observations']
for t, obs in enumerate(obs_list):
    print(obs.keys())
    print(obs['cmd_cartesian_states'].shape)
    print(obs['cmd_cartesian_states'], obs['gripper_states'])
    # base  = to_uint8(obs.get("pixels4"))
    # wrist = to_uint8(obs.get("pixels6"))

    # cart  = np.asarray(obs["cartesian_states"], dtype=np.float32).reshape(-1)[:6]
    # grip  = float(np.asarray(obs["gripper_states"]).reshape(-1)[0])
    # state = np.concatenate([cart, [grip]]).astype(np.float32)   # 7


# for i in range(1, 12, 2):
#     pkl_path = f"/home/bobby/Point-Policy/point_policy/robot_utils/franka/coordinates/place_bottle_from_the_fridge_left_robot/demonstration_{i}.pkl"
#     import pickle, pprint

#     with open(pkl_path, "rb") as f:
#         data = pickle.load(f)
#     print(data['cam_4'], data['cam_6'])
# pkl_path = "/home/bobby/Point-Policy/point_policy/robot_utils/franka/coordinates/place_bottle_from_the_fridge_left_robot/demonstration_1.pkl"
# import pickle, pprint

# with open(pkl_path, "rb") as f:
#     data = pickle.load(f)
# print(data['cam_4'], data['cam_6'])
# print(len(data['observations']))
# print(data['max_cartesian'])
# print(data['min_cartesian'])
# print(data['max_gripper'])
# print(data['min_gripper'])

# print("Top‑level type:", type(data))

# if isinstance(data, dict):
#     print("Dict keys:", data.keys())
#     # peek at one entry so you can see what it looks like
#     for k, v in data.items():
#         print(f"{k}: ({type(v)}, length={len(v) if hasattr(v,'__len__') else 'n/a'})")
#         break
# else:
#     # list / tuple / something else
#     print("Length:", len(data))
#     pprint.pprint(data[0], depth=2)   # look at the first element

# import pickle, pathlib, shutil

# pkl_path = "/home/bobby/data/expert_demos/franka_env/pick_plate_from_rack_left_robot.pkl"

# # 1) keep a safety copy
# backup = pathlib.Path(pkl_path).with_suffix(".bak")
# shutil.copy(pkl_path, backup)

# # 2) load, delete, save
# with open(pkl_path, "rb") as f:
#     data = pickle.load(f)

# obs_list = data.get("observations")
# if obs_list is None:
#     raise KeyError("'observations' key not found")

# # if len(obs_list) <= 13:
# #     raise IndexError("File contains fewer than 13 trajectories")

# # del obs_list[13]          # removes the 13‑th trajectory (index 12)
# # delete index 23, 24, 25
# del obs_list[7]
# del obs_list[1:4]       # removes the 24‑th, 25‑th, and 26‑th trajectories (indices 23, 24, 25)


# with open(pkl_path, "wb") as f:
#     pickle.dump(data, f)

# print("Deleted the 24‑th, 25‑th, and 26‑th trajectories. Backup written to", backup)


dict_keys(['observations', 'max_cartesian', 'min_cartesian', 'max_gripper', 'min_gripper'])
11
dict_keys(['pixels4', 'pixels6', 'cartesian_states', 'gripper_states', 'cmd_cartesian_states', 'cmd_gripper_states'])
(237, 6)
[[ 0.26540786  0.0252592   0.2743926   3.136016    0.04331319 -0.04293025]
 [ 0.26540786  0.0252592   0.2743926   3.136016    0.04331319 -0.04293025]
 [ 0.26540786  0.0252592   0.2743926   3.136016    0.04331319 -0.04293025]
 ...
 [ 0.3312764   0.13873038  0.3014467  -2.946517   -0.05225678 -0.08209555]
 [ 0.3312764   0.13873038  0.3014467  -2.946517   -0.05225678 -0.08209555]
 [ 0.3312764   0.13873038  0.3014467  -2.946517   -0.05225678 -0.08209555]] [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1.  1.  1.  1.  